// ============================================================
//  RollRef — data.js
//  Fonte central de dados do catálogo.
// ============================================================

export const modelos = [
  // ──────────────────────────────────────────────
  //  OXER
  // ──────────────────────────────────────────────
  {
    id: "oxer-secret-retro",
    nome: "Oxer Secret Retrô",
    marca: "Oxer",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "vinil sintético",
      cano: "alto",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "metal",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: null,
      durometro: null,
      quantidade: 4,
      obs: "rodas básicas — indicadas para piso liso",
    },
    rolamento: "ABEC 5",
    freio: "frontal fixo",
    preco_ref: "R$ 400 – R$ 480",
    disponibilidade: "Centauro",
    link_oficial: "https://www.centauro.com.br",
    obs: "Modelo clássico de visual retrô. Bota acolchoada e base em metal. Indicado para lazer em piso liso. Peças de reposição limitadas.",
    imagem: "/images/patins_inline.png", // placeholder
  },
  {
    id: "oxer-sweet-suede",
    nome: "Oxer Sweet Suede",
    marca: "Oxer",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "camurça sintética",
      cano: "alto",
      fechamento: ["cadarço"],
    },
    frame: {
      material: "metal",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: null,
      durometro: null,
      quantidade: 4,
      obs: "rodas básicas com freio de altura regulável",
    },
    rolamento: "ABEC 5",
    freio: "frontal com regulagem de altura",
    preco_ref: "R$ 380 – R$ 450",
    disponibilidade: "Centauro",
    link_oficial: "https://www.centauro.com.br",
    obs: "Visual artístico com bota em camurça sintética. Freio com regulagem é um diferencial para iniciantes. Fabricado na China.",
    imagem: "/images/patins_quad.png",
  },
  {
    id: "oxer-byte-adulto",
    nome: "Oxer Byte Adulto",
    marca: "Oxer",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot sintético",
      cano: "medio",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "plástico composto",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 7",
    freio: "heel brake traseiro",
    preco_ref: "R$ 400 – R$ 600",
    disponibilidade: "Centauro e lojas especializadas",
    link_oficial: "https://www.centauro.com.br",
    obs: "Modelo de entrada para adultos com rolamento ABEC 7. Boa relação custo-benefício para fitness e lazer urbano.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "oxer-freestyle-adulto",
    nome: "Oxer Freestyle Adulto",
    marca: "Oxer",
    tipo: "inline",
    categoria: "freestyle",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "hardboot PU",
      cano: "alto",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "84A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 9",
    freio: null,
    preco_ref: "R$ 600 – R$ 800",
    disponibilidade: "Centauro e lojas especializadas",
    link_oficial: "https://www.centauro.com.br",
    obs: "Base em alumínio e ABEC 9 sem freio voltado para freestyle e slalom. Boa opção nacional nessa faixa de preço.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "oxer-darkness-gold",
    nome: "Oxer Darkness Gold",
    marca: "Oxer",
    tipo: "inline",
    categoria: "freestyle",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "hardboot PU",
      cano: "alto",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "84A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 7",
    freio: null,
    preco_ref: "R$ 600 – R$ 850",
    disponibilidade: "Centauro e lojas especializadas",
    link_oficial: "https://www.centauro.com.br",
    obs: "Design premium com acabamento Gold. Base em alumínio e visual arrojado para freestyle.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "oxer-speed-7000-ajustavel",
    nome: "Oxer Speed 7000 Ajustável",
    marca: "Oxer",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto", "criança"],
    bota: {
      material: "plástico com estrutura em fibra de vidro",
      cano: "medio",
      fechamento: ["velcro", "fivela"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 300 – R$ 500",
    disponibilidade: "Centauro e lojas especializadas",
    link_oficial: "https://www.centauro.com.br",
    obs: "Modelo ajustável com base em alumínio e estrutura em fibra de vidro. Boa opção para quem está crescendo ou quer custo-benefício alto.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "oxer-alice-quad",
    nome: "Oxer Alice",
    marca: "Oxer",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "sintético estilo retrô",
      cano: "alto",
      fechamento: ["cadarço"],
    },
    frame: {
      material: "metal",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 58,
      durometro: "82A",
      quantidade: 4,
      obs: "rodas básicas para piso liso",
    },
    rolamento: "ABEC 5",
    freio: "frontal",
    preco_ref: "R$ 400 – R$ 550",
    disponibilidade: "Centauro e lojas especializadas",
    link_oficial: "https://www.centauro.com.br",
    obs: "Design retrô inspirado nos anos 70/80. Opção acessível para recreação em parques e rinques.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "oxer-algodao-doce-quad",
    nome: "Oxer Algodão Doce",
    marca: "Oxer",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "sintético colorido estilo retrô",
      cano: "alto",
      fechamento: ["cadarço"],
    },
    frame: {
      material: "metal",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 58,
      durometro: "82A",
      quantidade: 4,
      obs: "cores vibrantes combinando com a bota",
    },
    rolamento: "ABEC 5",
    freio: "frontal",
    preco_ref: "R$ 400 – R$ 550",
    disponibilidade: "Centauro e lojas especializadas",
    link_oficial: "https://www.centauro.com.br",
    obs: "Visual colorido e divertido estilo retrô. Boa opção para recreação casual.",
    imagem: "/images/patins_default.png",
  },

  // ──────────────────────────────────────────────
  //  ROLLER DERBY
  // ──────────────────────────────────────────────
  {
    id: "roller-derby-aerio-q60",
    nome: "Roller Derby Aerio Q60",
    marca: "Roller Derby",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "sintético macio (softboot)",
      cano: "alto",
      fechamento: ["cadarço", "velcro"],
    },
    frame: {
      material: "plástico reforçado",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 62,
      durometro: "82A",
      quantidade: 4,
      obs: "boa aderência em piso de madeira e asfalto liso",
    },
    rolamento: "ABEC 5",
    freio: "frontal removível",
    preco_ref: "R$ 350 – R$ 500",
    disponibilidade: "Lojas de esporte e e-commerce",
    link_oficial: "https://www.rollerderbyskates.com",
    obs: "Clássico da marca para recreação. Boa relação custo-benefício para quem está começando no quad.",
    imagem: "/images/roller-derby-aerio-q60.jpg",
  },
  {
    id: "roller-derby-v-tech-80",
    nome: "Roller Derby V-Tech 80",
    marca: "Roller Derby",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot sintético",
      cano: "medio",
      fechamento: ["cadarço", "fivela", "velcro"],
    },
    frame: {
      material: "nylon reforçado",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "boas para passeio urbano e ciclovia",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 300 – R$ 420",
    disponibilidade: "E-commerce e lojas esportivas",
    link_oficial: "https://www.rollerderbyskates.com",
    obs: "Entrada acessível no mundo do inline. Sistema triplo de fechamento garante segurança para iniciantes.",
    imagem: "/images/patins_inline.png",
  },
  {
    id: "roller-derby-aerio-q60-m",
    nome: "Roller Derby Aerio Q-60 M",
    marca: "Roller Derby",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot com espuma viscoelástica",
      cano: "medio",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "alumínio leve",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "80A",
      quantidade: 4,
      obs: "rodas Elite para asfalto e ciclovia",
    },
    rolamento: "Bevo Gold-7",
    freio: "heel brake traseiro",
    preco_ref: "R$ 400 – R$ 650",
    disponibilidade: "Amazon Brasil e e-commerce",
    link_oficial:
      "https://www.amazon.com.br/Roller-Derby-Patins-masculinos-Aerio/dp/B07TLP3D7K",
    obs: "Modelo fitness masculino com espuma viscoelástica para máximo conforto. Base em alumínio leve e rolamento Bevo Gold-7.",
    imagem: "/images/roller-derby-aerio-q60-m.jpg",
  },
  {
    id: "roller-derby-stryde-youth",
    nome: "Roller Derby Stryde Youth",
    marca: "Roller Derby",
    tipo: "inline",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["criança"],
    bota: {
      material: "plástico com forro acolchoado",
      cano: "medio",
      fechamento: ["velcro", "fivela"],
    },
    frame: {
      material: "plástico reforçado",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 72,
      durometro: "82A",
      quantidade: 4,
      obs: "uretano — indoor e outdoor",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 250 – R$ 400",
    disponibilidade: "Amazon Brasil e e-commerce",
    link_oficial: "https://www.amazon.com.br",
    obs: "Patins infantil ajustável em 4 tamanhos. Rodas de uretano versáteis para uso interno (rinque) e externo (asfalto liso).",
    imagem: "/images/roller-derby-stryde-youth.jpg",
  },
  {
    id: "roller-derby-fashion-quad",
    nome: "Roller Derby Fashion Quad",
    marca: "Roller Derby",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "sintético com acabamento fashion",
      cano: "alto",
      fechamento: ["cadarço"],
    },
    frame: {
      material: "plástico reforçado",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 62,
      durometro: "82A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 5",
    freio: "frontal",
    preco_ref: "R$ 350 – R$ 550",
    disponibilidade: "Roller Derby Brasil e e-commerce",
    link_oficial: "https://www.rollerderby.com.br",
    obs: "Design retrô e clássico para recreação em rinques e parques. Visual fashion com boa relação custo-benefício.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "roller-derby-star-600",
    nome: "Roller Derby Star 600",
    marca: "Roller Derby",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "sintético feminino",
      cano: "alto",
      fechamento: ["cadarço"],
    },
    frame: {
      material: "plástico reforçado",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 62,
      durometro: "82A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 5",
    freio: "frontal",
    preco_ref: "R$ 350 – R$ 500",
    disponibilidade: "Roller Derby Brasil e e-commerce",
    link_oficial: "https://www.rollerderby.com.br",
    obs: "Quad feminino adulto da linha Star. Design voltado para o público feminino com boa qualidade para recreação.",
    imagem: "/images/roller-derby-star-600.jpg",
  },
  {
    id: "roller-derby-star-350-girl",
    nome: "Roller Derby Star 350 Girl",
    marca: "Roller Derby",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["criança"],
    bota: {
      material: "sintético infantil feminino",
      cano: "alto",
      fechamento: ["cadarço", "velcro"],
    },
    frame: {
      material: "plástico reforçado",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 55,
      durometro: "82A",
      quantidade: 4,
      obs: "tamanho adaptado para crianças",
    },
    rolamento: "ABEC 3",
    freio: "frontal",
    preco_ref: "R$ 200 – R$ 350",
    disponibilidade: "Roller Derby Brasil e e-commerce",
    link_oficial: "https://www.rollerderby.com.br",
    obs: "Quad infantil feminino da linha Star. Design colorido e divertido para as primeiras experiências na patinação.",
    imagem: "/images/patins_default.png",
  },

  // ──────────────────────────────────────────────
  //  TRAXART
  // ──────────────────────────────────────────────
  {
    id: "traxart-revolt",
    nome: "Traxart Revolt",
    marca: "Traxart",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot) reforçado",
      cano: "alto",
      fechamento: ["cadarço", "fivela de catraca superior e inferior"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "4 rodas em linha (flat)",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "rodas de poliuretano de alta performance",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 900 – R$ 1.100",
    disponibilidade: "Traxart online e lojas especializadas",
    link_oficial: "https://www.traxart.com.br",
    obs: "Modelo clássico da linha Urban da Traxart. Muito resistente, ideal para saltos, descidas e patinação nas ruas.",
    imagem: "/images/traxart-revolt.jpg",
  },
  {
    id: "traxart-revolt-turbo",
    nome: "Traxart Revolt Turbo",
    marca: "Traxart",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot) com bota interna super acolchoada",
      cano: "alto",
      fechamento: ["cadarço", "fivela de catraca superior e inferior"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "3 rodas em linha (triskate)",
    },
    rodas: {
      diametro_mm: 110,
      durometro: "88A",
      quantidade: 3,
      obs: "rodas grandes para maior velocidade e superação de obstáculos",
    },
    rolamento: "ABEC 9 Cromo",
    freio: "sem freio",
    preco_ref: "R$ 1.200 – R$ 1.400",
    disponibilidade: "Traxart online e lojas especializadas",
    link_oficial: "https://www.traxart.com.br",
    obs: "Versão Triskate do Revolt. Rodas de 110mm garantem muita velocidade e fluidez na cidade. Indicado para patinadores experientes.",
    imagem: "/images/traxart-revolt-turbo.jpg",
  },
  {
    id: "traxart-fitness-80",
    nome: "Traxart Fitness 80",
    marca: "Traxart",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto", "criança"],
    bota: {
      material: "softboot com espuma EVA",
      cano: "medio",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "nylon",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "adequadas para asfalto e ciclovia",
    },
    rolamento: "ABEC 7",
    freio: "heel brake traseiro",
    preco_ref: "R$ 280 – R$ 380",
    disponibilidade: "Shopping centers e lojas de skate",
    link_oficial: "https://www.traxart.com.br",
    obs: "Uma das opções mais acessíveis com ABEC 7. Boa para quem quer começar sem gastar muito.",
    imagem: "/images/traxart-fitness-80.jpg",
  },
  {
    id: "traxart-volt-plus",
    nome: "Traxart Volt+",
    marca: "Traxart",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot)",
      cano: "alto",
      fechamento: ["cadarço", "fivela", "presilha micro ajustável"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "4 rodas em linha (rockeável)",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "rodas de poliuretano de alta resiliência",
    },
    rolamento: "ABEC 9 Cromo",
    freio: "sem freio",
    preco_ref: "R$ 1.000 – R$ 1.200",
    disponibilidade: "Traxart online e lojas parceiras",
    link_oficial: "https://www.traxart.com.br",
    obs: "Evolução do modelo Volt. Possui absorvedor de impacto e frame rockeável, excelente para urban e slalom.",
    imagem: "/images/patins_inline.png",
  },
  {
    id: "traxart-hype",
    nome: "Traxart Hype",
    marca: "Traxart",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "sintético reforçado (softboot)",
      cano: "alto",
      fechamento: ["cadarço"],
    },
    frame: {
      material: "alumínio",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 58,
      durometro: "83A",
      quantidade: 4,
      obs: "rodas em PU para asfalto liso ou rinque",
    },
    rolamento: "ABEC 7",
    freio: "frontal com regulagem",
    preco_ref: "R$ 800 – R$ 950",
    disponibilidade: "Traxart online",
    link_oficial: "https://www.traxart.com.br",
    obs: "Quad de nível intermediário com design moderno e confortável. A base em alumínio e o freio regulável são diferenciais chave.",
    imagem: "/images/traxart-hype.jpg",
  },
  {
    id: "traxart-dynamix",
    nome: "Traxart Dynamix",
    marca: "Traxart",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot)",
      cano: "alto",
      fechamento: ["cadarço", "fivela", "presilha"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "bom para asfalto",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 850 – R$ 1.050",
    disponibilidade: "Traxart online",
    link_oficial: "https://www.traxart.com.br",
    obs: "Opção muito escolhida pelo custo-benefício e durabilidade no urban.",
    imagem: "/images/traxart-dynamix.jpg",
  },
  {
    id: "traxart-mesh",
    nome: "Traxart Mesh",
    marca: "Traxart",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "tecido mesh respirável (softboot)",
      cano: "medio",
      fechamento: ["cadarço", "velcro", "fivela"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "ideal para ciclovias",
    },
    rolamento: "ABEC 7",
    freio: "traseiro",
    preco_ref: "R$ 600 – R$ 800",
    disponibilidade: "Traxart online",
    link_oficial: "https://www.traxart.com.br",
    obs: "Design voltado para extremo conforto e ventilação.",
    imagem: "/images/traxart-mesh.jpg",
  },
  {
    id: "traxart-jet",
    nome: "Traxart Inline Fitness Jet",
    marca: "Traxart",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot acolchoado",
      cano: "medio",
      fechamento: ["cadarço", "velcro", "fivela"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "piso liso e passeios suaves",
    },
    rolamento: "ABEC 7",
    freio: "traseiro",
    preco_ref: "R$ 550 – R$ 750",
    disponibilidade: "Traxart online e lojas parceiras",
    link_oficial: "https://www.traxart.com.br",
    obs: "Patins fitness com ótima relação custo-benefício.",
    imagem: "/images/traxart-jet.jpg",
  },
  {
    id: "traxart-electro-v2",
    nome: "Traxart Electro V2",
    marca: "Traxart",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot) reforçado",
      cano: "alto",
      fechamento: ["cadarço", "fivelas de alta precisão"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "3 rodas em linha (triskate)",
    },
    rodas: {
      diametro_mm: 110,
      durometro: "85A",
      quantidade: 3,
      obs: "rodas de alto desempenho",
    },
    rolamento: "ABEC 9 Cromo",
    freio: "sem freio",
    preco_ref: "R$ 1.300 – R$ 1.500",
    disponibilidade: "Traxart online",
    link_oficial: "https://www.traxart.com.br",
    obs: "Modelo triskate de visual impactante e componentes de alta performance.",
    imagem: "/images/traxart-electro-v2.jpg",
  },
  {
    id: "traxart-new-revolt-r3",
    nome: "Traxart New Revolt R3",
    marca: "Traxart",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido resistente",
      cano: "alto",
      fechamento: ["cadarço", "fivelas catraca"],
    },
    frame: {
      material: "alumínio CNC (híbrido)",
      configuracao: "3 ou 4 rodas",
    },
    rodas: {
      diametro_mm: 110,
      durometro: "88A",
      quantidade: 3,
      obs: "pode rodar com setup de 4 rodas menores também",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 1.400 – R$ 1.700",
    disponibilidade: "Traxart online",
    link_oficial: "https://www.traxart.com.br",
    obs: "A última geração do Revolt, com frame versátil que permite mudar o setup conforme o rolê.",
    imagem: "/images/traxart-new-revolt-r3.jpg",
  },
  {
    id: "traxart-street-aggressive",
    nome: "Traxart Street Aggressive",
    marca: "Traxart",
    tipo: "inline",
    categoria: "freestyle",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido com soulplate amplo",
      cano: "alto",
      fechamento: ["cadarço", "fivela superior", "velcro"],
    },
    frame: {
      material: "UFS composto (nylon/fibra)",
      configuracao: "anti-rocker (2 grandes, 2 pequenas no meio)",
    },
    rodas: {
      diametro_mm: 57,
      durometro: "90A",
      quantidade: 4,
      obs: "rodas nas pontas e grindwheels no meio",
    },
    rolamento: "ABEC 7",
    freio: "sem freio",
    preco_ref: "R$ 900 – R$ 1.200",
    disponibilidade: "Traxart online",
    link_oficial: "https://www.traxart.com.br",
    obs: "Voltado especificamente para manobras em skateparks e corrimãos (grinds).",
    imagem: "/images/traxart-street-aggressive.jpg",
  },
  {
    id: "traxart-atomix",
    nome: "Traxart Atomix",
    marca: "Traxart",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot)",
      cano: "alto",
      fechamento: ["cadarço", "fivela", "presilha"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "poliuretano alta durabilidade",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 900 – R$ 1.100",
    disponibilidade: "Traxart online",
    link_oficial: "https://www.traxart.com.br",
    obs: "Opção moderna para urban com excelente fluidez e estabilidade em curvas.",
    imagem: "/images/traxart-atomix.jpg",
  },
  {
    id: "traxart-slalom-pro",
    nome: "Traxart Slalom Pro",
    marca: "Traxart",
    tipo: "inline",
    categoria: "freestyle",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot)",
      cano: "alto",
      fechamento: ["cadarço", "fivela de catraca", "cuff ajustável"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha (rockeadas)",
    },
    rodas: {
      diametro_mm: 76,
      durometro: "85A",
      quantidade: 4,
      obs: "rodas rockeadas — pontas menores para facilitar manobras de slalom",
    },
    rolamento: "ABEC 7",
    freio: "sem freio (estilo freestyle)",
    preco_ref: "R$ 550 – R$ 750",
    disponibilidade: "Traxart online e lojas especializadas",
    link_oficial: "https://www.traxart.com.br",
    obs: "Bom custo-benefício para slalom. Base em alumínio é um diferencial nessa faixa de preço. Indicado para evolução técnica.",
    imagem: "/images/patins_quad.png",
  },

  // ──────────────────────────────────────────────
  //  FILA SKATES
  // ──────────────────────────────────────────────
  {
    id: "fila-houdini",
    nome: "Fila Skates Houdini",
    marca: "Fila Skates",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot) ventilado",
      cano: "alto",
      fechamento: ["cadarço", "fivela de catraca no cuff e peito do pé"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas (aceita configuração 3 rodas)",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "base híbrida que suporta tanto 4x80mm quanto 3x90mm",
    },
    rolamento: "ABEC 7",
    freio: "heel brake incluso (removível)",
    preco_ref: "R$ 950 – R$ 1.200",
    disponibilidade: "Lojas esportivas e e-commerce",
    link_oficial: "https://www.filaskates.com.br",
    obs: "Um dos urban mais versáteis do mercado graças ao seu frame híbrido. Hardboot muito confortável para pés levemente mais largos.",
    imagem: "/images/patins_inline.png",
  },
  {
    id: "fila-legacy-pro",
    nome: "Fila Skates Legacy Pro",
    marca: "Fila Skates",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot com reforço lateral",
      cano: "medio",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "composite plástico",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "80A",
      quantidade: 4,
      obs: "macias — boa aderência em piso urbano",
    },
    rolamento: "ABEC 7",
    freio: "heel brake traseiro",
    preco_ref: "R$ 400 – R$ 600",
    disponibilidade: "Lojas multimarcas e e-commerce",
    link_oficial: "https://www.filaskates.com.br",
    obs: "Modelo confiável com acabamento premium para o segmento de entrada. Boa opção de presente.",
    imagem: "/images/patins_speed.png",
  },
  {
    id: "fila-crossfit-84",
    nome: "Fila Skates Crossfit 84",
    marca: "Fila Skates",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "softboot reforçado",
      cano: "medio-alto",
      fechamento: ["cadarço", "fivela de catraca", "cuff"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 84,
      durometro: "84A",
      quantidade: 4,
      obs: "rodas maiores = mais velocidade em trajetos urbanos",
    },
    rolamento: "ABEC 9",
    freio: "heel brake traseiro removível",
    preco_ref: "R$ 700 – R$ 950",
    disponibilidade: "Lojas especializadas e e-commerce",
    link_oficial: "https://www.filaskates.com.br",
    obs: "Excelente para quem quer evoluir para o urban skating. Rolamento ABEC 9 e frame em alumínio são diferenciais nessa faixa.",
    imagem: "/images/patins_inline.png",
  },

  {
    id: "fila-skates-houdini-evo-pro-110",
    nome: "Fila Skates Houdini Evo PRO 110mm",
    marca: "Fila Skates",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "hardboot PU",
      cano: "alto",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "alumínio série 6000",
      configuracao: "3 rodas em linha",
    },
    rodas: {
      diametro_mm: 110,
      durometro: "85A",
      quantidade: 3,
      obs: "",
    },
    rolamento: "ABEC 7",
    freio: null,
    preco_ref: "R$ 1.200 – R$ 1.600",
    disponibilidade: "Savana Skate Shop e lojas especializadas",
    link_oficial: "https://www.savanaskateshop.com.br",
    obs: "Versão Evo PRO do Houdini com rodas de 110mm. Alta performance para urban e freeskate avançado.",
    imagem: "/images/fila-skates-houdini-evo-pro-110.jpg",
  },
  {
    id: "fila-skates-houdini-evo-pro-125",
    nome: "Fila Skates Houdini Evo PRO 125mm",
    marca: "Fila Skates",
    tipo: "inline",
    categoria: "speed",
    nivel: "profissional",
    publico: ["adulto"],
    bota: {
      material: "hardboot PU",
      cano: "alto",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "alumínio",
      configuracao: "3 rodas em linha",
    },
    rodas: {
      diametro_mm: 125,
      durometro: "85A",
      quantidade: 3,
      obs: "",
    },
    rolamento: "ABEC 9",
    freio: null,
    preco_ref: "R$ 1.500 – R$ 2.000",
    disponibilidade: "Savana Skate Shop e lojas especializadas",
    link_oficial: "https://www.savanaskateshop.com.br",
    obs: "Top de linha da série Houdini. Rodas de 125mm e ABEC 9 para máxima velocidade em percursos urbanos e competições.",
    imagem: "/images/fila-skates-houdini-evo-pro-125.jpg",
  },
  {
    id: "fila-skates-madame-houdini",
    nome: "Fila Skates Madame Houdini",
    marca: "Fila Skates",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "hardboot PU",
      cano: "alto",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "alumínio série 6000",
      configuracao: "4 rodas em linha (convertível 3x90mm)",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "base híbrida — convertível para tri skate 3x90mm",
    },
    rolamento: "ABEC 7",
    freio: "heel brake incluso (removível)",
    preco_ref: "R$ 900 – R$ 1.200",
    disponibilidade: "Fila Skates e lojas especializadas",
    link_oficial: "https://www.filaskates.com.br/madame-houdini",
    obs: "Versão feminina do Houdini com as mesmas funcionalidades de conversão para tri skate. Design dedicado ao público feminino.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "fila-skates-nrk-pro",
    nome: "Fila Skates NRK PRO",
    marca: "Fila Skates",
    tipo: "inline",
    categoria: "freestyle",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "hardboot PU",
      cano: "alto",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "84A",
      quantidade: 4,
      obs: "rodas intercambiáveis — sistema modular",
    },
    rolamento: "ABEC 7",
    freio: null,
    preco_ref: "R$ 1.200 – R$ 1.600",
    disponibilidade: "Fila Skates e lojas especializadas",
    link_oficial: "https://www.filaskates.com.br",
    obs: "Modelo altamente customizável com placas coloridas intercambiáveis. Referência no freeskate nacional.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "fila-skates-nrk-sd",
    nome: "Fila Skates NRK SD",
    marca: "Fila Skates",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "softboot com estrutura em fibra de carbono",
      cano: "medio",
      fechamento: ["cadarço", "fivela", "cuff ajustável"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 76,
      durometro: "84A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 7",
    freio: null,
    preco_ref: "R$ 1.000 – R$ 1.400",
    disponibilidade: "Fila Skates e lojas especializadas",
    link_oficial: "https://www.filaskates.com.br/nrk-sd",
    obs: "Softboot com reforço em fibra de carbono e cuff ajustável. Excelente responsividade para freeskate e urban avançado.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "fila-skates-nrk-fun",
    nome: "Fila Skates NRK Fun",
    marca: "Fila Skates",
    tipo: "inline",
    categoria: "freestyle",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "hardboot PU",
      cano: "alto",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "plástico composto",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 7",
    freio: null,
    preco_ref: "R$ 700 – R$ 950",
    disponibilidade: "Fila Skates e lojas especializadas",
    link_oficial: "https://www.filaskates.com.br",
    obs: "Modelo de entrada na linha NRK. Proteção Extreme Slider na lateral para iniciantes em freeskate e street.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "fila-skates-j-one",
    nome: "Fila Skates J-One",
    marca: "Fila Skates",
    tipo: "inline",
    categoria: "urban",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot reforçado",
      cano: "medio",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "plástico composto",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 7",
    freio: "heel brake traseiro",
    preco_ref: "R$ 400 – R$ 600",
    disponibilidade: "Fila Skates e lojas especializadas",
    link_oficial: "https://www.filaskates.com.br",
    obs: "Modelo de entrada da Fila Skates com cadarço e 2 alavancas micrométricas. Boa opção para iniciantes no inline.",
    imagem: "/images/patins_default.png",
  },

  // ──────────────────────────────────────────────
  //  BEL SPORTS
  // ──────────────────────────────────────────────
  {
    id: "bel-sports-inline-starter",
    nome: "Bel Sports Inline Starter",
    marca: "Bel Sports",
    tipo: "inline",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["criança", "adulto"],
    bota: {
      material: "plástico macio",
      cano: "baixo",
      fechamento: ["velcro", "fivela"],
    },
    frame: {
      material: "plástico",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 72,
      durometro: "82A",
      quantidade: 4,
      obs: "indicadas para piso liso — parque ou quadra",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 150 – R$ 250",
    disponibilidade: "Lojas de varejo — Americanas, Shopee, Mercado Livre",
    link_oficial: "https://www.belsports.com.br",
    obs: "Opção de entrada para crianças ou adultos que querem experimentar patinar antes de investir. Não indicado para uso frequente ou evolução técnica.",
    imagem: "/images/patins_speed.png",
  },
  {
    id: "bel-sports-quad-classic",
    nome: "Bel Sports Quad Classic",
    marca: "Bel Sports",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["criança"],
    bota: {
      material: "plástico com forro básico",
      cano: "alto",
      fechamento: ["cadarço", "velcro"],
    },
    frame: {
      material: "plástico",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 58,
      durometro: "82A",
      quantidade: 4,
      obs: "rodas pequenas — indicadas para crianças e pisos lisos",
    },
    rolamento: "ABEC 3",
    freio: "frontal",
    preco_ref: "R$ 120 – R$ 200",
    disponibilidade: "Varejo amplo — Americanas, Shopee, Mercado Livre",
    link_oficial: "https://www.belsports.com.br",
    obs: "Patins de entrada para crianças. Ideal para primeiros passos em casa ou parques tranquilos. Não recomendado para evolução técnica.",
    imagem: "/images/patins_quad.png",
  },
  {
    id: "bel-sports-top-premium-ajustavel",
    nome: "Bel Sports Top Premium Ajustável",
    marca: "Bel Sports",
    tipo: "inline",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto", "criança"],
    bota: {
      material: "softboot acolchoado",
      cano: "medio",
      fechamento: ["velcro", "fivela"],
    },
    frame: {
      material: "plástico",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 72,
      durometro: "82A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 150 – R$ 250",
    disponibilidade: "Bel Store e varejistas online",
    link_oficial: "https://www.belstore.com.br",
    obs: "Patins ajustável com bota softboot acolchoada. Indicado para primeiros passos em parques e piso liso.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "bel-sports-flexx-3-0-ajustavel",
    nome: "Bel Sports Flexx 3.0 Ajustável",
    marca: "Bel Sports",
    tipo: "inline",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto", "criança"],
    bota: {
      material: "plástico com forro básico",
      cano: "medio",
      fechamento: ["velcro", "fivela"],
    },
    frame: {
      material: "alumínio (truck e chassi)",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 72,
      durometro: "82A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 200 – R$ 350",
    disponibilidade: "Bel Store e varejistas online",
    link_oficial: "https://www.belstore.com.br",
    obs: "Modelo ajustável com truck e chassi em alumínio. Diferencial importante frente a concorrentes com frame de plástico na mesma faixa de preço.",
    imagem: "/images/bel-sports-flexx-3-0-ajustavel.jpg",
  },
  {
    id: "bel-sports-future-pro",
    nome: "Bel Sports Future Pro",
    marca: "Bel Sports",
    tipo: "inline",
    categoria: "fitness",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "softboot com ventilação lateral",
      cano: "medio",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "alumínio 100% (base, truck e chassi)",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "rodas PU de alta qualidade",
    },
    rolamento: "ABEC-7 Carbon",
    freio: "freio TPR traseiro",
    preco_ref: "R$ 400 – R$ 600",
    disponibilidade: "Bel Store e varejistas online",
    link_oficial: "https://www.belstore.com.br",
    obs: "Melhor modelo da linha Bel Sports. Base, truck e chassi 100% em alumínio e rolamento ABEC-7 Carbon são diferenciais para fitness.",
    imagem: "/images/bel-sports-future-pro.jpg",
  },

  // ──────────────────────────────────────────────
  //  POWERSLIDE
  // ──────────────────────────────────────────────
  {
    id: "powerslide-next-core-100",
    nome: "Powerslide Next Core Black 100",
    marca: "Powerslide",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto", "profissional"],
    bota: {
      material: "plástico rígido (hardboot)",
      cano: "alto ajustável",
      fechamento: ["cadarço", "fivela de catraca 45°", "cuff ajustável"],
    },
    frame: {
      material: "alumínio aeronáutico 6061",
      configuracao: "3 rodas em linha (sistema TRINITY 3-point mount)",
    },
    rodas: {
      diametro_mm: 100,
      durometro: "88A",
      quantidade: 3,
      obs: "Powerslide Spinner — alta velocidade e aderência em piso urbano",
    },
    rolamento: "Wicked ABEC 9",
    freio: "sem freio (urban freeride)",
    preco_ref: "R$ 1.500 – R$ 2.000",
    disponibilidade: "Lojas especializadas e importação",
    link_oficial: "https://www.powerslide.com",
    obs: "Referência no urban skating. Sistema TRINITY de 3 pontos reduz o centro de gravidade. Frame intercambiável. Patins para quem já domina a patinação.",
    imagem: "/images/powerslide-next-core-100.jpg",
  },
  {
    id: "powerslide-r6-marathon",
    nome: "Powerslide R6 Marathon",
    marca: "Powerslide",
    tipo: "inline",
    categoria: "speed",
    nivel: "avancado",
    publico: ["adulto", "profissional"],
    bota: {
      material: "plástico reforçado com fibra de vidro — feita à mão",
      cano: "baixo (speed boot)",
      fechamento: ["cadarço", "fivela de catraca 45°", "cuff de suporte"],
    },
    frame: {
      material: "alumínio CNC aeronáutico 6061",
      configuracao: "3 rodas em linha — 195mm / 3x125mm",
    },
    rodas: {
      diametro_mm: 125,
      durometro: "85A",
      quantidade: 3,
      obs: "Powerslide Infinity SHR (Super High Rebound) — máxima velocidade",
    },
    rolamento: "Wicked ABEC 9 — aço cromo",
    freio: "compatível com Megacruiser 125 (não incluso)",
    preco_ref: "R$ 2.200 – R$ 3.000",
    disponibilidade: "Lojas especializadas e importação",
    link_oficial: "https://www.powerslide.com",
    obs: "Patins de competição para maratonas e corridas. Bota manufaturada à mão com fibra de vidro. Máxima transferência de energia a cada pedalada. Não recomendado para iniciantes.",
    imagem: "/images/powerslide-r6-marathon.jpg",
  },
  {
    id: "powerslide-phuzion-argon-80",
    nome: "Powerslide Phuzion Argon 80",
    marca: "Powerslide",
    tipo: "inline",
    categoria: "urban",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot com reforço plástico",
      cano: "medio",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "plástico composto",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "82A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 600 – R$ 900",
    disponibilidade: "Inline Store e lojas especializadas",
    link_oficial: "https://www.inlinestore.com.br",
    obs: "Modelo de entrada da Powerslide na linha Phuzion. Porta de entrada para a marca com boa qualidade de construção.",
    imagem: "/images/powerslide-phuzion-argon-80.jpg",
  },
  {
    id: "powerslide-phuzion-universe",
    nome: "Powerslide Phuzion Universe",
    marca: "Powerslide",
    tipo: "inline",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["criança"],
    bota: {
      material: "plástico com forro acolchoado",
      cano: "medio",
      fechamento: ["velcro", "fivela"],
    },
    frame: {
      material: "plástico composto",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 72,
      durometro: "82A",
      quantidade: 4,
      obs: "tamanho adaptado para pés infantis",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 400 – R$ 650",
    disponibilidade: "Rolling Sports e lojas especializadas",
    link_oficial: "https://rollingsports.com.br",
    obs: "Patins infantil/juvenil ajustável (numeração 31–38). Qualidade Powerslide acessível para crianças.",
    imagem: "/images/powerslide-phuzion-universe.jpg",
  },
  {
    id: "powerslide-next-core-110",
    nome: "Powerslide Next Core 110",
    marca: "Powerslide",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot)",
      cano: "alto ajustável",
      fechamento: ["cadarço", "fivela de catraca 45°", "cuff ajustável"],
    },
    frame: {
      material: "alumínio aeronáutico 6061",
      configuracao: "3 rodas em linha (sistema TRINITY 3-point mount)",
    },
    rodas: {
      diametro_mm: 110,
      durometro: "88A",
      quantidade: 3,
      obs: "Powerslide Spinner — alta velocidade em piso urbano",
    },
    rolamento: "Wicked ABEC 9",
    freio: null,
    preco_ref: "R$ 1.800 – R$ 2.400",
    disponibilidade: "Inline Store e lojas especializadas",
    link_oficial: "https://www.inlinestore.com.br",
    obs: "Versão 110mm do Next Core com sistema TRINITY. Rodas maiores para mais velocidade sem perder controle urbano.",
    imagem: "/images/powerslide-next-core-110.jpg",
  },
  {
    id: "powerslide-swell-road-125",
    nome: "Powerslide Swell Road 125mm",
    marca: "Powerslide",
    tipo: "inline",
    categoria: "speed",
    nivel: "profissional",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido de alta performance",
      cano: "alto ajustável",
      fechamento: ["cadarço", "fivela de catraca", "cuff ajustável"],
    },
    frame: {
      material: "alumínio aeronáutico 6061",
      configuracao: "3 rodas em linha (sistema TRINITY 3-point mount)",
    },
    rodas: {
      diametro_mm: 125,
      durometro: "85A",
      quantidade: 3,
      obs: "rodas de 125mm — máxima velocidade em percursos urbanos",
    },
    rolamento: "Wicked ABEC 9",
    freio: null,
    preco_ref: "R$ 2.200 – R$ 3.000",
    disponibilidade: "Inline Store e lojas especializadas",
    link_oficial: "https://www.inlinestore.com.br",
    obs: "Top de linha da Powerslide para speed e urban. Sistema TRINITY com 3 rodas de 125mm para máxima eficiência energética.",
    imagem: "/images/powerslide-swell-road-125.jpg",
  },
  {
    id: "powerslide-imperial",
    nome: "Powerslide Imperial",
    marca: "Powerslide",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot)",
      cano: "alto",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "84A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 7",
    freio: null,
    preco_ref: "R$ 900 – R$ 1.300",
    disponibilidade: "Inline Store e lojas especializadas",
    link_oficial: "https://www.inlinestore.com.br",
    obs: "Modelo intermediário da Powerslide para freeskate e urban. Boa qualidade de construção e custo-benefício dentro da marca.",
    imagem: "/images/powerslide-imperial.jpg",
  },
  {
    id: "powerslide-puls-4x110",
    nome: "Powerslide Puls 4x110",
    marca: "Powerslide",
    tipo: "inline",
    categoria: "speed",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "softboot de alta rigidez",
      cano: "medio-alto",
      fechamento: ["cadarço", "fivela de catraca", "cuff ajustável"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 110,
      durometro: "85A",
      quantidade: 4,
      obs: "4 rodas de 110mm para maratonas e fitness de alta intensidade",
    },
    rolamento: "ABEC 9",
    freio: null,
    preco_ref: "R$ 1.500 – R$ 2.200",
    disponibilidade: "Inline Store e lojas especializadas",
    link_oficial: "https://www.inlinestore.com.br",
    obs: "Setup de 4x110mm para maior estabilidade em alta velocidade. Equilibra a velocidade do triskate com a estabilidade de 4 rodas.",
    imagem: "/images/powerslide-puls-4x110.jpg",
  },

  // ──────────────────────────────────────────────
  //  K2
  // ──────────────────────────────────────────────
  {
    id: "k2-kinetic-80",
    nome: "K2 Kinetic 80",
    marca: "K2",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot K2 Original com Stability Plus Cuff",
      cano: "medio",
      fechamento: ["cadarço", "velcro", "presilhas plásticas"],
    },
    frame: {
      material: "composto plástico F.B.I. (Frame Boot Integration)",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "80A",
      quantidade: 4,
      obs: "poliuretano — macias e estáveis para iniciantes",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 600 – R$ 850",
    disponibilidade: "Lojas especializadas e e-commerce",
    link_oficial: "https://www.k2skates.com",
    obs: "Softboot confortável com ótimo suporte de tornozelo. Ideal para fitness e lazer urbano. A tecnologia F.B.I. integra bota e base para melhor resposta.",
    imagem: "/images/k2-kinetic-80.jpg",
  },
  {
    id: "k2-vo2-s-100",
    nome: "K2 VO2 S 100",
    marca: "K2",
    tipo: "inline",
    categoria: "fitness",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "softboot com reforço estrutural",
      cano: "medio-alto",
      fechamento: ["cadarço", "fivela de catraca", "cuff ajustável"],
    },
    frame: {
      material: "alumínio — quadro unilateral VO2-S",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 100,
      durometro: "85A",
      quantidade: 4,
      obs: "rodas grandes para alta velocidade e performance em trajetos longos",
    },
    rolamento: "ABEC 7",
    freio: "heel brake traseiro removível",
    preco_ref: "R$ 1.100 – R$ 1.500",
    disponibilidade: "Lojas especializadas e importação",
    link_oficial: "https://www.k2skates.com",
    obs: "Quadro unilateral VO2-S dá visibilidade completa das rodas de 100mm. Voltado para performance em longas distâncias. Ótima escolha para treinamentos X-Training.",
    imagem: "/images/patins_quad.png",
  },
  {
    id: "k2-kinetic-80-w",
    nome: "K2 Kinetic 80 W",
    marca: "K2",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot K2 Original com Stability Plus Cuff",
      cano: "medio",
      fechamento: ["cadarço", "velcro", "presilhas plásticas"],
    },
    frame: {
      material: "composto plástico F.B.I. (Frame Boot Integration)",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "80A",
      quantidade: 4,
      obs: "poliuretano — macias e estáveis para iniciantes",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 600 – R$ 850",
    disponibilidade: "Lojas especializadas e e-commerce",
    link_oficial:
      "https://www.brasilinline.com.br/patins-inline-k2-kinetic-80-w",
    obs: "Versão feminina do Kinetic 80. Mesmas características técnicas com numeração e design voltados para o público feminino.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "k2-kinetic-80-pro-m",
    nome: "K2 Kinetic 80 Pro M",
    marca: "K2",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot K2 Original com Stability Plus Cuff",
      cano: "medio",
      fechamento: ["cadarço", "velcro", "presilhas plásticas"],
    },
    frame: {
      material: "composto plástico F.B.I.",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "80A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 700 – R$ 950",
    disponibilidade: "Lojas especializadas e e-commerce",
    link_oficial: "https://www.brasilinline.com.br",
    obs: "Versão Pro do Kinetic 80 masculino com upgrade estético e acabamento superior. Mesma tecnologia F.B.I. e suporte de tornozelo.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "k2-kinetic-80-pro-w",
    nome: "K2 Kinetic 80 Pro W",
    marca: "K2",
    tipo: "inline",
    categoria: "fitness",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "softboot K2 Original com Stability Plus Cuff",
      cano: "medio",
      fechamento: ["cadarço", "velcro", "presilhas plásticas"],
    },
    frame: {
      material: "composto plástico F.B.I.",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "80A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 700 – R$ 950",
    disponibilidade: "Lojas especializadas e e-commerce",
    link_oficial: "https://www.brasilinline.com.br",
    obs: "Versão Pro feminina do Kinetic 80. Upgrade estético com design voltado para o público feminino.",
    imagem: "/images/k2-kinetic-80-pro-w.jpg",
  },
  {
    id: "k2-fit-80-boa",
    nome: "K2 F.I.T. 80 BOA",
    marca: "K2",
    tipo: "inline",
    categoria: "fitness",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "softboot com reforço estrutural",
      cano: "medio",
      fechamento: ["cadarço", "BOA"],
    },
    frame: {
      material: "composto plástico F.B.I.",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "80A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 5",
    freio: "heel brake traseiro",
    preco_ref: "R$ 800 – R$ 1.100",
    disponibilidade: "Lojas especializadas e e-commerce",
    link_oficial: "https://www.brasilinline.com.br",
    obs: "Diferencial é o sistema de fechamento BOA para ajuste milimétrico rápido com uma mão. Ideal para treinos frequentes.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "k2-vo2-s-90-m",
    nome: "K2 VO2 S 90 M",
    marca: "K2",
    tipo: "inline",
    categoria: "fitness",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "softboot com ventilação Vortech",
      cano: "medio-alto",
      fechamento: ["cadarço", "fivela de catraca", "cuff ajustável"],
    },
    frame: {
      material: "alumínio — quadro unilateral VO2-S",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 90,
      durometro: "85A",
      quantidade: 4,
      obs: "rodas de 90mm para equilíbrio entre velocidade e controle",
    },
    rolamento: "ABEC 7",
    freio: "heel brake traseiro removível",
    preco_ref: "R$ 900 – R$ 1.200",
    disponibilidade: "Lojas especializadas e e-commerce",
    link_oficial: "https://www.brasilinline.com.br/patins-inline-k2-vo2-s-90-m",
    obs: "Versão 90mm do VO2 S com base alumínio unilateral e sistema de ventilação Vortech. Ótimo para x-training e fitness intermediário.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "k2-vo2-s-100-boa",
    nome: "K2 VO2 S 100 BOA",
    marca: "K2",
    tipo: "inline",
    categoria: "fitness",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "softboot com reforço estrutural aeroespacial",
      cano: "medio-alto",
      fechamento: ["cadarço", "BOA", "cuff ajustável"],
    },
    frame: {
      material: "alumínio aeroespacial — quadro unilateral VO2-S",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 100,
      durometro: "85A",
      quantidade: 4,
      obs: "rodas grandes para alta velocidade e performance em trajetos longos",
    },
    rolamento: "ABEC 7",
    freio: "heel brake traseiro removível",
    preco_ref: "R$ 1.300 – R$ 1.700",
    disponibilidade: "Lojas especializadas e e-commerce",
    link_oficial:
      "https://www.brasilinline.com.br/patins-inline-k2-vo2-s-100-boa",
    obs: "Versão premium do VO2 S com fechamento BOA e base alumínio aeroespacial. Ajuste preciso para treinamentos intensos de longa distância.",
    imagem: "/images/patins_default.png",
  },
  {
    id: "k2-mod-110",
    nome: "K2 MOD 110",
    marca: "K2",
    tipo: "inline",
    categoria: "speed",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "softboot de alta rigidez com suporte de tornozelo reforçado",
      cano: "baixo",
      fechamento: ["cadarço", "fivela de catraca"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 110,
      durometro: "85A",
      quantidade: 4,
      obs: "rodas de 110mm para máxima velocidade em maratonas",
    },
    rolamento: "ILQ-9 Pro",
    freio: null,
    preco_ref: "R$ 1.500 – R$ 2.000",
    disponibilidade: "Lojas especializadas e e-commerce",
    link_oficial: "https://www.brasilinline.com.br/patins-inline-k2-mod-110",
    obs: "Patins de velocidade com 4 rodas de 110mm e rolamentos ILQ-9 Pro. Voltado para maratonistas e competição de longa distância.",
    imagem: "/images/k2-mod-110.jpg",
  },

  // ──────────────────────────────────────────────
  //  ROCES
  // ──────────────────────────────────────────────
  {
    id: "roces-kolossal",
    nome: "Roces Kolossal",
    marca: "Roces",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "sintético estilo tênis cano alto",
      cano: "alto",
      fechamento: ["cadarço"],
    },
    frame: {
      material: "metal",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 62,
      durometro: "82A",
      quantidade: 4,
      obs: "macias — rodam bem em piso irregular",
    },
    rolamento: "ABEC 5",
    freio: "frontal",
    preco_ref: "R$ 500 – R$ 700",
    disponibilidade: "RollerJam e lojas especializadas",
    link_oficial: "https://www.roces.com",
    obs: "Design moderno estilo tênis cano alto. Confortável para fins de semana. As rodas macias funcionam bem em piso irregular — diferencial frente a outros quads da categoria.",
    imagem: "/images/roces-kolossal.jpg",
  },
  {
    id: "roces-disco-palace",
    nome: "Roces Disco Palace",
    marca: "Roces",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "couro sintético estilo retrô",
      cano: "alto",
      fechamento: ["cadarço"],
    },
    frame: {
      material: "metal",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 62,
      durometro: "82A",
      quantidade: 4,
      obs: "macias e versáteis para piso de madeira e asfalto",
    },
    rolamento: "ABEC 5",
    freio: "frontal",
    preco_ref: "R$ 550 – R$ 750",
    disponibilidade: "RollerJam e lojas especializadas",
    link_oficial: "https://www.roces.com",
    obs: "Visual retrô inspirado na era disco. Marca europeia com padrão de qualidade acima da média nessa faixa de preço. Muito procurado por fãs do estilo quad vintage.",
    imagem: "/images/roces-disco-palace.jpg",
  },
  {
    id: "roces-m12-recycle",
    nome: "Roces M12 Recycle",
    marca: "Roces",
    tipo: "inline",
    categoria: "agressivo",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico reciclado reforçado",
      cano: "alto",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "plástico UFS (Universal Frame System)",
      configuracao: "4 rodas em linha (anti-rocker disponível)",
    },
    rodas: {
      diametro_mm: 58,
      durometro: "88A",
      quantidade: 4,
      obs: "rodas pequenas para street e grinds",
    },
    rolamento: "ABEC 3",
    freio: null,
    preco_ref: "R$ 700 – R$ 1.000",
    disponibilidade: "Brasil Inline e lojas especializadas",
    link_oficial:
      "https://www.brasilinline.com.br/patins-in-line-roces-m12-recycle-black",
    obs: "Versão eco-friendly do M12 com estrutura em material reciclado. Sistema UFS compatível com frames do mercado.",
    imagem: "/images/roces-m12-recycle.jpg",
  },
  {
    id: "roces-m12-lo-team",
    nome: "Roces M12 Lo Team",
    marca: "Roces",
    tipo: "inline",
    categoria: "agressivo",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido com cuff baixo",
      cano: "baixo",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "plástico UFS",
      configuracao: "anti-rocker (2 rodas grandes + 2 grindwheels)",
    },
    rodas: {
      diametro_mm: 59,
      durometro: "90A",
      quantidade: 4,
      obs: "fivelas de memória em alumínio — anti-rocker de fábrica",
    },
    rolamento: "ABEC 5",
    freio: null,
    preco_ref: "R$ 900 – R$ 1.200",
    disponibilidade: "Brasil Inline e lojas especializadas",
    link_oficial:
      "https://www.brasilinline.com.br/patins-in-line-roces-m12-lo-team-juno",
    obs: "Versão cuff baixo do M12 Team. Fivelas de memória em alumínio e anti-rocker de fábrica para street skating profissional.",
    imagem: "/images/roces-m12-lo-team.jpg",
  },
  {
    id: "roces-m12-lo-savosin",
    nome: "Roces M12 Lo Savosin",
    marca: "Roces",
    tipo: "inline",
    categoria: "agressivo",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "plástico com PU de base biológica",
      cano: "baixo",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "plástico UFS",
      configuracao: "anti-rocker",
    },
    rodas: {
      diametro_mm: 60,
      durometro: "92A",
      quantidade: 4,
      obs: "rodas duras para máxima resposta em grinds",
    },
    rolamento: "ABEC 5",
    freio: null,
    preco_ref: "R$ 1.100 – R$ 1.400",
    disponibilidade: "Brasil Inline e lojas especializadas",
    link_oficial:
      "https://www.brasilinline.com.br/patins-in-line-roces-m12-lo-savosin-heat-",
    obs: "Edição assinada pelo atleta Savosin. PU de base biológica e rodas 92A para street avançado.",
    imagem: "/images/roces-m12-lo-savosin.jpg",
  },
  {
    id: "roces-m12-lo-goto-namikaze",
    nome: "Roces M12 Lo Goto Namikaze",
    marca: "Roces",
    tipo: "inline",
    categoria: "agressivo",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "plástico eco-friendly reforçado",
      cano: "baixo",
      fechamento: ["cadarço", "fivela"],
    },
    frame: {
      material: "fibra de vidro UFS",
      configuracao: "anti-rocker",
    },
    rodas: {
      diametro_mm: 60,
      durometro: "93A",
      quantidade: 4,
      obs: "rodas extremamente duras para precisão máxima em grinds",
    },
    rolamento: "ABEC 5",
    freio: null,
    preco_ref: "R$ 1.200 – R$ 1.600",
    disponibilidade: "Brasil Inline e lojas especializadas",
    link_oficial:
      "https://www.brasilinline.com.br/patins-in-line-roces-m12-lo-goto-namizake",
    obs: "Edição assinada pelo atleta Goto Namikaze. Frame em fibra de vidro e materiais eco-friendly. Rodas 93A das mais duras disponíveis.",
    imagem: "/images/roces-m12-lo-goto-namikaze.jpg",
  },
  {
    id: "roces-rc1-quad",
    nome: "Roces RC1",
    marca: "Roces",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "couro ecológico",
      cano: "alto",
      fechamento: ["cadarço"],
    },
    frame: {
      material: "metal",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 62,
      durometro: "82A",
      quantidade: 4,
      obs: "",
    },
    rolamento: "ABEC 5",
    freio: "frontal",
    preco_ref: "R$ 500 – R$ 750",
    disponibilidade: "Amazon Brasil e lojas especializadas",
    link_oficial:
      "https://www.amazon.com.br/Roces-patinadores-fundamental-intermediario-confortaveis/dp/B0D1WC5W9N",
    obs: "Quad europeu com bota em couro ecológico. Boa qualidade de acabamento para recreação e iniciação artística.",
    imagem: "/images/roces-rc1-quad.jpg",
  },

  // ──────────────────────────────────────────────
  //  HD INLINE
  // ──────────────────────────────────────────────
  {
    id: "hd-inline-bold",
    nome: "HD Inline BOLD",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido resistente",
      cano: "alto",
      fechamento: ["cadarço", "fivela", "presilha"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "rodas de poliuretano de alta resistência",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 999,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Lançamento. Patins robusto para manobras e patinação urbana.",
    imagem: "/images/hd-inline-bold.jpg",
  },
  {
    id: "hd-inline-rt-urban",
    nome: "HD Inline RT URBAN",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido (hardboot)",
      cano: "alto",
      fechamento: ["cadarço", "fivela superior", "presilha"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "disponível nas cores cinza, verde e vermelho",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 999,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Design urbano focado em estabilidade. Disponível em várias cores: cinza, verde e vermelho.",
    imagem: "/images/hd-inline-rt-urban.jpg",
  },
  {
    id: "hd-inline-bw7",
    nome: "HD Inline BW7",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto"],
    bota: {
      material: "plástico reforçado de alta durabilidade",
      cano: "alto",
      fechamento: ["cadarço", "fivelas micrométricas"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "alta performance em piso de asfalto",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 999,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Modelo profissional voltado para patinadores experientes que buscam máxima resposta.",
    imagem: "/images/hd-inline-bw7.jpg",
  },
  {
    id: "hd-inline-skull-2-5",
    nome: "HD Inline SKULL 2.5",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "hardboot estilizado",
      cano: "alto",
      fechamento: ["cadarço", "fivela de precisão"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "rodas duráveis para uso diário",
    },
    rolamento: "ABEC 7",
    freio: "sem freio",
    preco_ref: "R$ 799,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Design urbano arrojado e disponível em várias cores. Excelente custo-benefício.",
    imagem: "/images/hd-inline-skull-2-5.jpg",
  },
  {
    id: "hd-inline-sky",
    nome: "HD Inline SKY",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido com forro respirável",
      cano: "alto",
      fechamento: ["cadarço", "fivelas ajustáveis"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "versátil para passeios urbanos",
    },
    rolamento: "ABEC 7",
    freio: "sem freio",
    preco_ref: "R$ 799,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Disponível nas versões Black Stone e Tradicional.",
    imagem: "/images/hd-inline-sky.jpg",
  },
  {
    id: "hd-inline-tracker",
    nome: "HD Inline TRACKER",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "hardboot performance",
      cano: "alto",
      fechamento: ["cadarço", "presilha"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "foco em performance",
    },
    rolamento: "ABEC 7",
    freio: "sem freio",
    preco_ref: "R$ 799,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Modelo focado em performance urbana e precisão nas manobras.",
    imagem: "/images/hd-inline-tracker.jpg",
  },
  {
    id: "hd-inline-evolution-ii-80",
    nome: "HD Inline EVOLUTION II (4x80mm)",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto", "profissional"],
    bota: {
      material: "hardboot de precisão profissional",
      cano: "alto",
      fechamento: ["cadarço", "fivelas de alta segurança"],
    },
    frame: {
      material: "alumínio CNC ultra resistente",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "rodas de alta performance",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 1.399,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Alta performance e nível profissional. Ideal para saltos e slides intensos.",
    imagem: "/images/hd-inline-evolution-ii-80.jpg",
  },
  {
    id: "hd-inline-evolution-ii-110",
    nome: "HD Inline EVOLUTION II (3x110mm)",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "urban",
    nivel: "avancado",
    publico: ["adulto", "profissional"],
    bota: {
      material: "hardboot de precisão profissional",
      cano: "alto",
      fechamento: ["cadarço", "fivelas de alta segurança"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "3 rodas em linha (triskate)",
    },
    rodas: {
      diametro_mm: 110,
      durometro: "88A",
      quantidade: 3,
      obs: "rodas de 110mm para alta velocidade e absorção de impacto em asfalto irregular",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 1.399,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Versão triskate para alta velocidade nas ruas, sem abrir mão do controle.",
    imagem: "/images/hd-inline-evolution-ii-110.jpg",
  },
  {
    id: "hd-inline-carbon-cruiser",
    nome: "HD Inline CARBON CRUISER",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "speed",
    nivel: "avancado",
    publico: ["adulto", "profissional"],
    bota: {
      material: "fibra de carbono ultraleve",
      cano: "baixo/médio",
      fechamento: ["cadarço", "fivelas milimétricas"],
    },
    frame: {
      material: "alumínio CNC de alta classe",
      configuracao: "3 ou 4 rodas dependendo do setup",
    },
    rodas: {
      diametro_mm: 110,
      durometro: "88A",
      quantidade: 3,
      obs: "alto desempenho em retas e maratonas",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 1.999,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Estrutura super leve com base em carbono. Para patinadores de velocidade e maratona que buscam alto desempenho.",
    imagem: "/images/hd-inline-carbon-cruiser.jpg",
  },
  {
    id: "hd-inline-panther",
    nome: "HD Inline PANTHER",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "freestyle",
    nivel: "avancado",
    publico: ["adulto", "profissional"],
    bota: {
      material: "plástico super resistente a impactos severos",
      cano: "alto",
      fechamento: ["cadarço", "fivela de pressão e velcro"],
    },
    frame: {
      material: "composto nylon/fibra de vidro UFS",
      configuracao: "anti-rocker ou flat",
    },
    rodas: {
      diametro_mm: 58,
      durometro: "90A",
      quantidade: 4,
      obs: "rodas pequenas para street",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 1.999,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "O ápice do street da HD Inline. Controle total, resistência extrema e soulplate generoso para deslizar em qualquer superfície.",
    imagem: "/images/hd-inline-panther.jpg",
  },
  {
    id: "hd-inline-cherry-quad",
    nome: "HD Inline Cherry Quad",
    marca: "HD Inline",
    tipo: "quad",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["adulto"],
    bota: {
      material: "sintético aveludado ou com glitter",
      cano: "alto",
      fechamento: ["cadarço"],
    },
    frame: {
      material: "alumínio",
      configuracao: "quad (2x2)",
    },
    rodas: {
      diametro_mm: 58,
      durometro: "82A",
      quantidade: 4,
      obs: "Poliuretano macio para absorção de vibrações",
    },
    rolamento: "ABEC 7",
    freio: "frontal",
    preco_ref: "R$ 559,84",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Disponível em acabamentos incríveis: preto glitter, preto veludo, preto e rosa. Base em alumínio para maior resistência.",
    imagem: "/images/hd-inline-cherry-quad.jpg",
  },
  {
    id: "hd-inline-zippy",
    nome: "HD Inline ZIPPY Ajustável",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "recreativo",
    nivel: "iniciante",
    publico: ["criança"],
    bota: {
      material: "plástico rígido com bota interna confortável",
      cano: "alto",
      fechamento: ["cadarço", "velcro", "presilha ajustável"],
    },
    frame: {
      material: "plástico de alta resistência",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 72,
      durometro: "82A",
      quantidade: 4,
      obs: "rodas de tamanho adaptável à bota infantil",
    },
    rolamento: "ABEC 5",
    freio: "traseiro removível",
    preco_ref: "R$ 599,90",
    disponibilidade: "HD Inline oficial",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Patins infantil com sistema expansível de tamanhos. Conforto e segurança para os pequenos iniciarem na patinação.",
    imagem: "/images/hd-inline-zippy.jpg",
  },
  {
    id: "hd-inline-black",
    nome: "HD Inline Black",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido resistente a impactos",
      cano: "alto",
      fechamento: ["cadarço", "fivela de catraca superior e peito do pé"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 80,
      durometro: "85A",
      quantidade: 4,
      obs: "bom desempenho em asfalto rugoso",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 800 – R$ 1.000",
    disponibilidade: "Lojas especializadas",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Opção nacional robusta e com ótimo custo-benefício para quem quer entrar no patins street/urban sem investir valores exorbitantes.",
    imagem: "/images/hd-inline-black.jpg",
  },
  {
    id: "hd-inline-speed-110",
    nome: "HD Inline Speed 110",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "speed",
    nivel: "avancado",
    publico: ["adulto", "profissional"],
    bota: {
      material: "fibra de carbono / plástico de alta rigidez",
      cano: "baixo (speed boot)",
      fechamento: ["cadarço", "fivela de catraca"],
    },
    frame: {
      material: "alumínio CNC",
      configuracao: "3 rodas em linha",
    },
    rodas: {
      diametro_mm: 110,
      durometro: "85A",
      quantidade: 3,
      obs: "rodas de alta performance para velocidade máxima",
    },
    rolamento: "ABEC 9",
    freio: "sem freio",
    preco_ref: "R$ 1.800 – R$ 2.500",
    disponibilidade: "Lojas especializadas em patinação",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Voltado para patinadores de velocidade e competição. Alta rigidez e leveza são o foco do modelo. Exige domínio completo da técnica de freagem sem freio.",
    imagem: "/images/patins_inline.png",
  },
  {
    id: "hd-inline-urban-90",
    nome: "HD Inline Urban 90",
    marca: "HD Inline",
    tipo: "inline",
    categoria: "urban",
    nivel: "intermediario",
    publico: ["adulto"],
    bota: {
      material: "plástico rígido com forro confortável",
      cano: "alto",
      fechamento: ["cadarço", "fivela", "cuff"],
    },
    frame: {
      material: "alumínio",
      configuracao: "4 rodas em linha",
    },
    rodas: {
      diametro_mm: 90,
      durometro: "85A",
      quantidade: 4,
      obs: "versáteis para asfalto, ciclovia e piso de parque",
    },
    rolamento: "ABEC 7",
    freio: "heel brake removível",
    preco_ref: "R$ 900 – R$ 1.300",
    disponibilidade: "Lojas especializadas em patinação",
    link_oficial: "https://www.hdinline.com.br",
    obs: "Bom ponto de entrada no urban skating. Equilibra conforto e performance. Indicado para quem já sabe patinar e quer evoluir o estilo.",
    imagem: "/images/patins_speed.png",
  },
];

// ─────────────────────────────────────────
//  FUNÇÕES UTILITÁRIAS
// ─────────────────────────────────────────

export function getTodosModelos() {
  return modelos;
}

export function filtrarPorTipo(tipo) {
  return modelos.filter((m) => m.tipo === tipo);
}

export function filtrarPorNivel(nivel) {
  return modelos.filter((m) => m.nivel === nivel);
}

export function filtrarPorCategoria(categoria) {
  return modelos.filter((m) => m.categoria === categoria);
}

export function filtrarPorMarca(marca) {
  return modelos.filter((m) => m.marca.toLowerCase() === marca.toLowerCase());
}

export function buscarPorNome(texto) {
  if (!texto) return modelos;
  const q = texto.toLowerCase();
  return modelos.filter(
    (m) =>
      m.nome.toLowerCase().includes(q) || m.marca.toLowerCase().includes(q),
  );
}

export function getModeloPorId(id) {
  return modelos.find((m) => m.id === id) || null;
}

export function getMarcas() {
  return [...new Set(modelos.map((m) => m.marca))].sort();
}

export function getCategorias() {
  return [...new Set(modelos.map((m) => m.categoria))].sort();
}
